name: Run Python Script

on:
  schedule:
    - cron: '*/30 * * * *'  # 每半小时触发一次
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Python Script
      run: |
        python ss.py  # 自动运行 ss.py 脚本

    - name: Upload Output
      uses: actions/upload-artifact@v3
      with:
        name: output-file
        path: output.txt
