name: Sync to Gitee

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # 确保完整克隆

    - name: Add Gitee Remote
      run: |
        git remote add gitee https://oauth2:${{ secrets.GITEE_TOKEN }}@gitee.com/gentleleaf/ss.git

    - name: Push to Gitee
      run: |
        git push gitee main --force
